# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnboardingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for OnboardingApp
  pod 'SnapKit'
  pod 'SwiftLint'

  target 'OnboardingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnboardingAppUITests' do
    # Pods for testing
  end

end
